# Generated by Django 5.1.1 on 2024-09-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=8)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='pending', max_length=15)),
                ('is_sub_task', models.BooleanField(default=False)),
                ('has_sub_tasks', models.BooleanField(default=False)),
                ('sub_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='project.task')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_title', models.CharField(max_length=100)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('pending', 'Pending'), ('initiated', 'Initiated'), ('upcoming', 'Upcoming'), ('inactive', 'Inactive')], default='inactive', max_length=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.projectcategory')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='project.task')),
            ],
        ),
    ]
